// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by class UIConstantFiles.
// Make any needed changes in class UIConstantFiles.

namespace NotificationLooker.Systems
{
    public class UIEventName
    {
        // Events group name.
        public const string GroupName = "NotificationLooker";

        // Events from UI to C#.
        public const string MainButtonClicked = "mainButtonClicked";
        public const string MainPanelMoved = "mainPanelMoved";

        // Events from C# to UI for main panel.
        public const string MainPanelUISettings = "mainPanelUISettings";
        public const string NotificationData = "notificationData";
        public const string NotificationClicked = "notificationClicked";
    }

    public class UITranslationKey
    {
        // Mod title and description.
        public const string Title = "NotificationLooker.Title";
        public const string Description = "NotificationLooker.Description";
        public const string Shortcut = "NotificationLooker.Shortcut";

        // Settings.
        public const string SettingTitle = "Options.SECTION[NotificationLooker.NotificationLooker.Mod]";
        public const string SettingBindingMap = "Options.INPUT_MAP[NotificationLooker.NotificationLooker.Mod]";
        public const string SettingGroupGeneral = "Options.GROUP[NotificationLooker.NotificationLooker.Mod.General]";
        public const string SettingActivationKeyBinding = "Options.OPTION[NotificationLooker.NotificationLooker.Mod/ActivationKeyBinding/binding]";
        public const string SettingActivationKeyBindingLabel = "Options.OPTION[NotificationLooker.NotificationLooker.Mod.ModSettings.ActivationKeyBinding]";
        public const string SettingActivationKeyBindingDesc = "Options.OPTION_DESCRIPTION[NotificationLooker.NotificationLooker.Mod.ModSettings.ActivationKeyBinding]";
        public const string SettingResetWindowPositionLabel = "Options.OPTION[NotificationLooker.NotificationLooker.Mod.ModSettings.ResetMainPanelPosition]";
        public const string SettingResetWindowPositionDesc = "Options.OPTION_DESCRIPTION[NotificationLooker.NotificationLooker.Mod.ModSettings.ResetMainPanelPosition]";
        public const string SettingGroupAbout = "Options.GROUP[NotificationLooker.NotificationLooker.Mod.About]";
        public const string SettingModVersionLabel = "Options.OPTION[NotificationLooker.NotificationLooker.Mod.ModSettings.ModVersion]";
        public const string SettingModVersionDesc = "Options.OPTION_DESCRIPTION[NotificationLooker.NotificationLooker.Mod.ModSettings.ModVersion]";
    }
}