// DO NOT MODIFY THIS FILE.
// This entire file was automatically generated by class UIConstantFiles.
// Make any needed changes in class UIConstantFiles.

export class UIEventName
{
    // Events group name.
    public static GroupName: string = "NotificationLooker";

    // Events from UI to C#.
    public static MainButtonClicked: string = "mainButtonClicked";
    public static MainPanelMoved: string = "mainPanelMoved";

    // Events from C# to UI for main panel.
    public static MainPanelUISettings: string = "mainPanelUISettings";
    public static NotificationGroupedData: string = "notificationGroupedData";
    public static NotificationItemData: string = "notificationItemData";

    public static NotificationClicked: string = "notificationClicked";
}

export class UITranslationKey
{
    // Mod title and description.
    public static Title: string = "NotificationLooker.Title";
    public static Description: string = "NotificationLooker.Description";
    public static Shortcut: string = "NotificationLooker.Shortcut";

    // Settings.
    public static SettingTitle: string = "Options.SECTION[NotificationLooker.NotificationLooker.Mod]";
    public static SettingBindingMap: string = "Options.INPUT_MAP[NotificationLooker.NotificationLooker.Mod]";
    public static SettingGroupGeneral: string = "Options.GROUP[NotificationLooker.NotificationLooker.Mod.General]";
    public static SettingActivationKeyBinding: string = "Options.OPTION[NotificationLooker.NotificationLooker.Mod/ActivationKeyBinding/binding]";
    public static SettingActivationKeyBindingLabel: string = "Options.OPTION[NotificationLooker.NotificationLooker.Mod.ModSettings.ActivationKeyBinding]";
    public static SettingActivationKeyBindingDesc: string = "Options.OPTION_DESCRIPTION[NotificationLooker.NotificationLooker.Mod.ModSettings.ActivationKeyBinding]";
    public static SettingResetWindowPositionLabel: string = "Options.OPTION[NotificationLooker.NotificationLooker.Mod.ModSettings.ResetMainPanelPosition]";
    public static SettingResetWindowPositionDesc: string = "Options.OPTION_DESCRIPTION[NotificationLooker.NotificationLooker.Mod.ModSettings.ResetMainPanelPosition]";
    public static SettingGroupAbout: string = "Options.GROUP[NotificationLooker.NotificationLooker.Mod.About]";
    public static SettingModVersionLabel: string = "Options.OPTION[NotificationLooker.NotificationLooker.Mod.ModSettings.ModVersion]";
    public static SettingModVersionDesc: string = "Options.OPTION_DESCRIPTION[NotificationLooker.NotificationLooker.Mod.ModSettings.ModVersion]";
}